# Form implementation generated from reading ui file 'UserManagerUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

"""
用户管理界面,包括主界面，添加用户界面，删除用户界面，查找用户界面
"""

from PyQt6 import QtCore, QtWidgets, QtGui


class Ui_UserManager(QtWidgets.QWidget):
    switched_to_addUser = QtCore.pyqtSignal()
    switched_to_changeUser = QtCore.pyqtSignal()
    switched_to_menu = QtCore.pyqtSignal()
    switched_to_findUser = QtCore.pyqtSignal()
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, UserManager):
        UserManager.setObjectName("UserManager")
        UserManager.resize(1920, 1080 )
        self.pushButton = QtWidgets.QPushButton(parent=UserManager)
        self.pushButton.setGeometry(QtCore.QRect(400, 270, 151, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=UserManager)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 270, 151, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=UserManager)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 360, 151, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=UserManager)
        self.pushButton_4.setGeometry(QtCore.QRect(700, 360, 151, 71))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(UserManager)
        QtCore.QMetaObject.connectSlotsByName(UserManager)
        self.pushButton.clicked.connect(self.addUser)
        self.pushButton_2.clicked.connect(self.findUser)
        self.pushButton_3.clicked.connect(self.changeUser)
        self.pushButton_4.clicked.connect(self.menu)

    def retranslateUi(self, UserManager):
        _translate = QtCore.QCoreApplication.translate
        UserManager.setWindowTitle(_translate("UserManager", "Form"))
        self.pushButton.setText(_translate("UserManager", "新增账号"))
        self.pushButton_2.setText(_translate("UserManager", "查找账号"))
        self.pushButton_3.setText(_translate("UserManager", "修改账号"))
        self.pushButton_4.setText(_translate("UserManager", "返回"))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton_2.setFont(font)
        self.pushButton_3.setFont(font)
        self.pushButton_4.setFont(font)


    def addUser(self):
        self.switched_to_addUser.emit()

    def changeUser(self):
        self.switched_to_changeUser.emit()

    def menu(self):
        self.switched_to_menu.emit()

    def findUser(self):
        self.switched_to_findUser.emit()


