# Form implementation generated from reading ui file 'UserFindUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
"""
UserFindUI.py
用户信息查询界面,显示所有用户信息
"""

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem

from Function.UserManager import UserManager


class Ui_FindUser(QtWidgets.QWidget):
    switched_to_UserManager = QtCore.pyqtSignal()

    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, UserFind):
        """
        :param UserFind:
        :return:
        """
        UserFind.setObjectName("UserFind")
        UserFind.resize(1280, 720)
        self.tableWidget = QtWidgets.QTableWidget(parent=UserFind)
        self.tableWidget.setGeometry(QtCore.QRect(300, 180, 600, 300))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.pushButton_2 = QtWidgets.QPushButton(parent=UserFind)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 600, 230, 70))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.switch_to_UserManager)

        self.retranslateUi(UserFind)
        QtCore.QMetaObject.connectSlotsByName(UserFind)
        self.show_data()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "返回"))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)

    def show_data(self):
        """
        显示所有用户信息
        """
        user = UserManager()
        data = user.load_data()  # 获取所有用户信息
        self.tableWidget.setRowCount(len(data))
        self.tableWidget.setColumnCount(len(data[0]))
        self.tableWidget.setItem(0, 0, QTableWidgetItem("用户ID"))  # 设置表头
        self.tableWidget.setItem(0, 1, QTableWidgetItem("用户名"))
        self.tableWidget.setItem(0, 2, QTableWidgetItem("用户密码"))
        self.tableWidget.setItem(0, 3, QTableWidgetItem("用户权限"))
        for i, row in enumerate(data):
            for j, value in enumerate(row):
                if j == 3:  # 将权限数字转换为文字
                    if value == 0:
                        value = "园长"
                    elif value == 1:
                        value = "教师"
                    elif value == 2:
                        value = "保健老师"
                    elif value == None:
                        value = "未设置"
                self.tableWidget.setItem(i + 1, j, QTableWidgetItem(str(value)))

    def switch_to_UserManager(self):
        self.switched_to_UserManager.emit()
