# Form implementation generated from reading ui file 'UserFindUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem

from Function.UserManager import UserManager


class Ui_FindUser(QtWidgets.QWidget):
    switched_to_UserManager = QtCore.pyqtSignal()

    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, UserFind):
        """
        :todo 需要添加实现和提交修改、删除用户、返回上一层的功能
        :param UserFind:
        :return:
        """
        UserFind.setObjectName("UserFind")
        UserFind.resize(1108, 858)
        self.tableWidget = QtWidgets.QTableWidget(parent=UserFind)
        self.tableWidget.setGeometry(QtCore.QRect(30, 20, 500, 400))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(parent=UserFind)
        self.pushButton.setGeometry(QtCore.QRect(270, 600, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=UserFind)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 600, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.switch_to_UserManager)

        self.retranslateUi(UserFind)
        QtCore.QMetaObject.connectSlotsByName(UserFind)
        self.show_data()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "提交修改"))
        self.pushButton_2.setText(_translate("Form", "返回"))

    def show_data(self):
        """
        :todo 需要曾加表头
        :return:
        """
        user = UserManager()
        data = user.load_data()
        self.tableWidget.setRowCount(len(data))
        self.tableWidget.setColumnCount(len(data[0]))
        for i, row in enumerate(data):
            for j, value in enumerate(row):
                self.tableWidget.setItem(i, j, QTableWidgetItem(str(value)))

    def switch_to_UserManager(self):
        self.switched_to_UserManager.emit()
