# Form implementation generated from reading ui file 'LibraryManager.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import QMessageBox
from Function.BooksManager import BooksManager

class Ui_LibraryManager(QtWidgets.QWidget):
    switched_to_menu = pyqtSignal()

    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(190, 80, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(300, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(280, 220, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(290, 340, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(290, 280, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(220, 400, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(300, 460, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(220, 560, 270, 71))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        # self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        # self.pushButton_2.setGeometry(QtCore.QRect(590, 560, 270, 71))
        #font = QtGui.QFont()
        #font.setFamily("Adobe 黑体 Std R")
        #font.setPointSize(12)
        #self.pushButton_2.setFont(font)
        #self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(930, 560, 270, 71))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(450, 70, 351, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(450, 140, 351, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(450, 210, 351, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(450, 270, 351, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(450, 340, 351, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(450, 400, 351, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(450, 460, 351, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit.editingFinished.connect(self.get_book)
        self.has = 0
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.update_books)
        self.pushButton_3.clicked.connect(self.switch_to_main_widget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "请扫描书的条形码"))
        self.label_2.setText(_translate("Form", "书名"))
        self.label_3.setText(_translate("Form", "出版社"))
        self.label_4.setText(_translate("Form", "价格"))
        self.label_5.setText(_translate("Form", "作者"))
        self.label_6.setText(_translate("Form", "目前所在地址"))
        self.label_7.setText(_translate("Form", "本数"))
        self.pushButton.setText(_translate("Form", "提交"))
        #self.pushButton_2.setText(_translate("Form", "修改"))
        self.pushButton_3.setText(_translate("Form", "返回"))

    def get_book(self):
        isbn = self.lineEdit.text()
        self.book = BooksManager()
        data = self.book.query_sql(isbn)
        print(data)
        if data:
            self.lineEdit_2.setText(data[0][1])
            self.lineEdit_3.setText(data[0][2])
            self.lineEdit_5.setText(data[0][3])
            self.lineEdit_4.setText(data[0][4])
            self.lineEdit_6.setText(data[0][5])
            self.lineEdit_7.setText(str(data[0][6]))
            self.has = 1
        else:
            data = self.book.on_query(isbn)
            if data:
                self.lineEdit_2.setText(data['result']['title'])
                self.lineEdit_3.setText(data['result']['publisher'])
                self.lineEdit_5.setText(data['result']['price'])
                self.lineEdit_4.setText(data['result']['author'])
            self.has = 0

    def update_books(self):
        list1 = []
        list1.append(self.lineEdit.text())
        list1.append(self.lineEdit_2.text())
        list1.append(self.lineEdit_3.text())
        list1.append(self.lineEdit_4.text())
        list1.append(self.lineEdit_5.text())
        list1.append(self.lineEdit_6.text())
        list1.append(self.lineEdit_7.text())
        if self.has == 1:
            if self.book.update_book(list1):
                QMessageBox.information(self, '提示', '修改失败')
            else:
                QMessageBox.information(self, '提示', '修改成功')
        else:
            if self.book.add_book(list1):
                QMessageBox.information(self, '提示', '添加失败')
            else:
                QMessageBox.information(self, '提示', '添加成功')

    def switch_to_main_widget(self):
        self.switched_to_menu.emit()














