# Form implementation generated from reading ui file 'StudentsFindDaily.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from Function.StudentsManager import StudentsManager


class Ui_StudentsFindDaily(QtWidgets.QWidget):
    switched_to_student_manager_page = QtCore.pyqtSignal()
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 1241, 631))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(940, 650, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.load_data()
        self.pushButton.clicked.connect(self.switch_to_student_manager_page)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "返回"))

    def switch_to_student_manager_page(self):
        self.switched_to_student_manager_page.emit()

    def load_data(self):
        stu = StudentsManager()
        data = stu.get_stu_daily_attend()
        self.tableWidget.setRowCount(len(data))
        self.tableWidget.setColumnCount(len(data[0]))
        self.tableWidget.setHorizontalHeaderLabels(["日期", "学生姓名", "班级", "是否病假", "具体请假原因", "联系人"])
        for i in range(len(data)):
            for j in range(len(data[0])):
                self.tableWidget.setItem(i, j, QtWidgets.QTableWidgetItem(str(data[i][j])))

