# Form implementation generated from reading ui file 'LoginWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import QWidget

from Function.Login import Login


class LoginUI(QWidget):
    login_success = pyqtSignal()
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1116, 852)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(340, 180, 391, 51))
        self.label.setObjectName("label")
        self.label.setText("欢迎使用幼儿园信息管理系统")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(370, 320, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_2.setText("用户名")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(480, 310, 211, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(380, 420, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_3.setText("密  码")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(480, 410, 211, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(460, 570, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("登录")
        self.pushButton.clicked.connect(self.login)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
    def login(self):
        username = self.lineEdit.text()
        password = self.lineEdit_2.text()
        if Login().login(username, password):
            self.login_success.emit()
        else:
            self.label.setText("登录失败")
