# Form implementation generated from reading ui file 'UserManagerUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6 import QtCore, QtWidgets


class Ui_UserManager(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, UserManager):
        UserManager.setObjectName("UserManager")
        UserManager.resize(1113, 869)
        self.pushButton = QtWidgets.QPushButton(parent=UserManager)
        self.pushButton.setGeometry(QtCore.QRect(270, 200, 151, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=UserManager)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 200, 151, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=UserManager)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 370, 151, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=UserManager)
        self.pushButton_4.setGeometry(QtCore.QRect(630, 370, 151, 71))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(UserManager)
        QtCore.QMetaObject.connectSlotsByName(UserManager)

    def retranslateUi(self, UserManager):
        _translate = QtCore.QCoreApplication.translate
        UserManager.setWindowTitle(_translate("UserManager", "Form"))
        self.pushButton.setText(_translate("UserManager", "新增账号"))
        self.pushButton_2.setText(_translate("UserManager", "查找账号"))
        self.pushButton_3.setText(_translate("UserManager", "查找账号"))
        self.pushButton_4.setText(_translate("UserManager", "删除账号"))

