# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt6 import QtWidgets

from UI.LoginWidget import LoginUI
from PyQt6.QtWidgets import QStackedWidget, QMainWindow, QApplication
from UI.MainWidget import Ui_MainFunction
from UI.UserManagerUI import Ui_UserManager


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 863)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.stacked_widget = QStackedWidget()
        self.setCentralWidget(self.stacked_widget)
        self.login_page = LoginUI()
        self.main_function_page = Ui_MainFunction()
        self.userManager_page = Ui_UserManager()
        self.stacked_widget.addWidget(self.login_page)
        self.stacked_widget.addWidget(self.main_function_page)
        self.stacked_widget.addWidget(self.userManager_page)
        self.login_page.login_success.connect(self.show_main_function)
        self.main_function_page.switched_to_userManager.connect(self.show_user_manager)
        self.stacked_widget.setCurrentWidget(self.login_page)

    def show_main_function(self):
        self.stacked_widget.setCurrentWidget(self.main_function_page)\

    def show_user_manager(self):
        self.stacked_widget.setCurrentWidget(self.userManager_page)



